### ISSUE TITLE
java.lang.AssertionError in JSON verify method

### ISSUE THREAD

**Issue by timperrett** [szeiger/extradoc#3]
Hey hey,

Awesome work on this - it looks great. I made a script for unix that you may want to include (https://gist.github.com/802052) that does the same thing as your windows bat file. 

However, when I run it (documenting extradoc itself as there are no deps) I get the following error (with scala 2.8.0 on the path):

λ bin/extradoc.sh    -doc-format:explorer   -doc-title "ExtraDoc"   -doc-version 2.8.0   -d docs src/
model contains 31 documentable templates
java.lang.AssertionError: assertion failed
    at scala.Predef$.assert(Predef.scala:77)
    at com.novocode.extradoc.json.AbstractJsonFactory$$anon$2.<init>(AbstractJsonFactory.scala:211)
    at com.novocode.extradoc.json.AbstractJsonFactory.copyResource(AbstractJsonFactory.scala:209)
    at com.novocode.extradoc.json.JsonMultiFactory.generate(JsonMultiFactory.scala:30)
    at com.novocode.extradoc.DocFactory.document(DocFactory.scala:61)
    at com.novocode.extradoc.ExtraDoc$.process(ExtraDoc.scala:82)
    at com.novocode.extradoc.ExtraDoc$.main(ExtraDoc.scala:98)
    at com.novocode.extradoc.ExtraDoc.main(ExtraDoc.scala)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at scala.tools.nsc.util.ScalaClassLoader$$anonfun$run$1.apply(ScalaClassLoader.scala:81)
    at scala.tools.nsc.util.ScalaClassLoader$class.asContext(ScalaClassLoader.scala:24)
    at scala.tools.nsc.util.ScalaClassLoader$URLClassLoader.asContext(ScalaClassLoader.scala:86)
    at scala.tools.nsc.util.ScalaClassLoader$class.run(ScalaClassLoader.scala:81)
    at scala.tools.nsc.util.ScalaClassLoader$URLClassLoader.run(ScalaClassLoader.scala:86)
    at scala.tools.nsc.MainGenericRunner$.main(MainGenericRunner.scala:83)
    at scala.tools.nsc.MainGenericRunner.main(MainGenericRunner.scala)

Cheers, Tim

**Comment by szeiger** [comment]
I think there's an extraneous dot in your tool classpath so it can't find the resources. Try this instead: https://gist.github.com/802063

**Comment by timperrett** [comment]
Ah doh - stupid me; thanks for spotting that. Feel free to use the script or whatever alongside your bat if you like :-) Cheers, and great work on this - its excellent.

**Comment by szeiger** [comment]
Script added to master
